model_dir: ../models/translater_zh2en
ae_model_dir: ../models/set2seq/Quora-light-5

data:
  train_features_file: ../data/train.en.bpe
  train_labels_file: ../data/train.zh.bpe
  eval_features_file: ../data/test/test.en.bpe
  eval_labels_file: ../data/test/test.zh
  source_words_vocabulary: ../vocab/vocab.zh
  target_words_vocabulary: ../vocab/vocab.en

ae_data:
  source_words_vocabulary: ../vocab/vocab.en 
  target_words_vocabulary: ../vocab/vocab.en

train:
  save_checkpoints_steps: 2000

eval:
  external_evaluators: BLEU
  eval_delay: 1200

infer:
  batch_size: 32
